var text1 = "Die Emission von Europa ist ";
var text2 = "Relativ zur Gesamtemission der Welt verursacht Europa damit ";
var text3 = "Für Europa hat sich 2018 im Vergleich zu 2008 die Emission um ";
var text4 = "verändert";
var text5 = "2018 im Vergleich zu 2008 sind das ";
var europa = 4209.3;
var europa8 = 4965.7;
var gesamt = (europa + afrika + asien + australien + namerika + samerika);
var text6 = "Die Emission von Afrika ist ";
var text7 = "Relativ zur Gesamtemission der Welt verursacht Afrika damit ";
var text8 = "Für Afrika hat sich 2018 im Vergleich zu 2008 die Emission um ";
var afrika = 1235.5;
var afrika8 = 1028;
var text9 = "Die Emission von Asien ist ";
var text10 = "Relativ zur Gesamtemission der Welt verursacht Asien damit ";
var text11 = "Für Asien hat sich 2018 im Vergleich zu 2008 die Emission um ";
var asien = 16274.1;
var asien8 = 12954.7;
var text12 = "Die Emission von Australien ist ";
var text13 = "Relativ zur Gesamtemission der Welt verursacht Australien damit ";
var text14 = "Für Australien hat sich 2018 im Vergleich zu 2008 die Emission um ";
var australien = 2100.5;
var australien8 = 1993;
var text15 = "Die Emission von Nord Amerika ist ";
var text16 = "Relativ zur Gesamtemission der Welt verursacht Nord Amerika damit ";
var text17 = "Für Nord Amerika hat sich 2018 im Vergleich zu 2008 die Emission um ";
var namerika = 6035.6;
var namerika8 = 6600.4;
var text18 = "Die Emission von Süd Amerika ist ";
var text19 = "Relativ zur Gesamtemission der Welt verursacht Süd Amerika damit ";
var text20 = "Für Süd Amerika hat sich 2018 im Vergleich zu 2008 die Emission um ";
var samerika = 1261.5;
var samerika8 = 1132.6;
console.log(text1 + europa + "kg CO2");
console.log(text2 + (europa / gesamt) * 100 + "%");
console.log(text3 + (europa / europa8 - 1) * 100 + "%");
console.log(text4);
console.log(text5 + (europa - europa8) + "kg CO2");
console.log(text6 + afrika + "kg CO2");
console.log(text7 + (afrika / gesamt) * 100 + "%");
console.log(text8 + (europa / europa8 - 1) * 100 + "%");
console.log(text4);
console.log(text5 + (afrika - afrika8) + "kg CO2");
console.log(text9 + asien + "kg CO2");
console.log(text10 + (asien / gesamt) * 100 + "%");
console.log(text11 + (asien / asien8 - 1) * 100 + "%");
console.log(text4);
console.log(text5 + (asien - asien8) + "kg CO2");
console.log(text12 + australien + "kg CO2");
console.log(text13 + (australien / gesamt) * 100 + "%");
console.log(text14 + (australien / australien8 - 1) * 100 + "%");
console.log(text4);
console.log(text5 + (australien - australien8) + "kg CO2");
console.log(text15 + namerika + "kg CO2");
console.log(text16 + (namerika / gesamt) * 100 + "%");
console.log(text17 + (namerika / namerika8 - 1) * 100 + "%");
console.log(text4);
console.log(text5 + (namerika - namerika8) + "kg CO2");
console.log(text18 + samerika + "kg CO2");
console.log(text19 + (samerika / gesamt) * 100 + "%");
console.log(text20 + (samerika / samerika8 - 1) * 100 + "%");
console.log(text4);
console.log(text5 + (samerika - samerika8) + "kg CO2");
//# sourceMappingURL=test.js.map